### ISSUE TITLE
Membership page CSS messed up

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/calconnect.github.io#6]
Original:
<img width="572" alt="Screenshot 2024-12-03 at 6 39 21 PM" src="https://github.com/user-attachments/assets/aaa58a35-a33b-454c-802f-7fc76e3e8d45">

Now:
<img width="579" alt="Screenshot 2024-12-03 at 6 39 35 PM" src="https://github.com/user-attachments/assets/d853ed2a-bc12-4e81-a3db-65a8c07ad665">

**Comment by MuhammadAhsan252** [comment]
@ronaldtse Currently it's in asciidoc due to which css is applied properly. We can html here for better styling.

**Comment by ronaldtse** [comment]
I believe we can still handle this in AsciiDoc content and by changing the CSS that applies here.
